FROM jupyter/minimal-notebook
# pip3 is already installed thank god
RUN pip3 install matplotlib
# No EXPOSE is needed --> already exposed by jupyter
# No command is needed -->  the container will run the jupyter CMD 
